name: deploy

on:
  # 支持手动触发构建
  workflow_dispatch:
  release:
    types: [released]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取源码
        uses: actions/checkout@v2
      - name: Set up Apache Maven Central
        uses: actions/setup-java@v4
        with:
          java-version: 8.0.302+8
          distribution: 'temurin'
          cache: maven
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.GPG_SECRET }}
      - name: Publish to Apache Maven Central
        run: mvn deploy 
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USER }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSWORD }}